PATH_TESSERACT = '/usr/bin/tesseract'
USERS_DATA = 'users_data'
STOP_WORK = 'Да, работа с файлом завершена'
CONTINUE_WORK = 'Нет, хочу поработать с файлом'
GET_TEXT = 'Получить текст в сообщении'
GET_FILE = 'Получить текст в файле'